// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMkyUpltNoqGMLGqKjmfyENKE4JkgR3cQ',
    appId: '1:529775655888:web:6de9a31dfdd00d3e1497d5',
    messagingSenderId: '529775655888',
    projectId: 'thptexamprepapp',
    authDomain: 'thptexamprepapp.firebaseapp.com',
    storageBucket: 'thptexamprepapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAunczv2aEIwkv4UYO4Gbh2IOXX0Nr5MYA',
    appId: '1:529775655888:android:5085cee4bf39d9a51497d5',
    messagingSenderId: '529775655888',
    projectId: 'thptexamprepapp',
    storageBucket: 'thptexamprepapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq5VYd3xu6qQcVlJbphQer4kgEmcl7pkM',
    appId: '1:529775655888:ios:85d85995ced53a941497d5',
    messagingSenderId: '529775655888',
    projectId: 'thptexamprepapp',
    storageBucket: 'thptexamprepapp.firebasestorage.app',
    iosBundleId: 'com.example.thptExamPrepApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq5VYd3xu6qQcVlJbphQer4kgEmcl7pkM',
    appId: '1:529775655888:ios:85d85995ced53a941497d5',
    messagingSenderId: '529775655888',
    projectId: 'thptexamprepapp',
    storageBucket: 'thptexamprepapp.firebasestorage.app',
    iosBundleId: 'com.example.thptExamPrepApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMkyUpltNoqGMLGqKjmfyENKE4JkgR3cQ',
    appId: '1:529775655888:web:729c892ff3be19d11497d5',
    messagingSenderId: '529775655888',
    projectId: 'thptexamprepapp',
    authDomain: 'thptexamprepapp.firebaseapp.com',
    storageBucket: 'thptexamprepapp.firebasestorage.app',
  );
}

