/// Mock data for 9 THPT subjects
import 'package:thpt_exam_prep_app/models.dart';

class MockSubjectsData {
  static final List<Subject> subjects = [
    Subject(
      id: 'subj_001',
      name: 'Toán',
      description: 'Ôn tập Toán lớp 12 cho kỳ thi THPT',
      totalTopics: 8,
      totalDocuments: 15,
      totalExams: 5,
      iconUrl: '📐',
      color: '#FF6B6B',
      createdAt: DateTime.now(),
    ),
    Subject(
      id: 'subj_002',
      name: 'Ngữ Văn',
      description: 'Ôn tập Ngữ Văn lớp 12 cho kỳ thi THPT',
      totalTopics: 6,
      totalDocuments: 12,
      totalExams: 4,
      iconUrl: '📚',
      color: '#4ECDC4',
      createdAt: DateTime.now(),
    ),
    Subject(
      id: 'subj_003',
      name: 'Tiếng Anh',
      description: 'Ôn tập Tiếng Anh lớp 12 cho kỳ thi THPT',
      totalTopics: 7,
      totalDocuments: 14,
      totalExams: 4,
      iconUrl: '🌍',
      color: '#45B7D1',
      createdAt: DateTime.now(),
    ),
    Subject(
      id: 'subj_004',
      name: 'Vật Lý',
      description: 'Ôn tập Vật Lý lớp 12 cho kỳ thi THPT',
      totalTopics: 5,
      totalDocuments: 10,
      totalExams: 3,
      iconUrl: '⚡',
      color: '#F38181',
      createdAt: DateTime.now(),
    ),
    Subject(
      id: 'subj_005',
      name: 'Hóa Học',
      description: 'Ôn tập Hóa Học lớp 12 cho kỳ thi THPT',
      totalTopics: 5,
      totalDocuments: 10,
      totalExams: 3,
      iconUrl: '⚗️',
      color: '#95E1D3',
      createdAt: DateTime.now(),
    ),
    Subject(
      id: 'subj_006',
      name: 'Sinh Học',
      description: 'Ôn tập Sinh Học lớp 12 cho kỳ thi THPT',
      totalTopics: 4,
      totalDocuments: 8,
      totalExams: 3,
      iconUrl: '🧬',
      color: '#FE7C8A',
      createdAt: DateTime.now(),
    ),
    Subject(
      id: 'subj_007',
      name: 'Lịch Sử',
      description: 'Ôn tập Lịch Sử lớp 12 cho kỳ thi THPT',
      totalTopics: 4,
      totalDocuments: 9,
      totalExams: 3,
      iconUrl: '📜',
      color: '#C09E87',
      createdAt: DateTime.now(),
    ),
    Subject(
      id: 'subj_008',
      name: 'Địa Lý',
      description: 'Ôn tập Địa Lý lớp 12 cho kỳ thi THPT',
      totalTopics: 4,
      totalDocuments: 8,
      totalExams: 3,
      iconUrl: '🌏',
      color: '#A8E6CF',
      createdAt: DateTime.now(),
    ),
    Subject(
      id: 'subj_009',
      name: 'Giáo dục kinh tế và pháp luật',
      description: 'Ôn tập GDKTPL lớp 12 cho kỳ thi THPT',
      totalTopics: 3,
      totalDocuments: 6,
      totalExams: 2,
      iconUrl: '⚖️',
      color: '#FFD93D',
      createdAt: DateTime.now(),
    ),
  ];
}
